import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import Logo from "../components/Logo";
import Navigation from "../components/Navigation";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "The Wild Oasis",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{ children: React.ReactNode }>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <div className="container mx-auto px-10 py-5">
          <div className="flex flex-col min-h-screen">
            <header>
              <Logo />
              <Navigation />
            </header>
            <main>{children}</main>
            <footer className="py-5">
              Copyright by The Wild Oasis
            </footer>
          </div>
        </div>
      </body>
    </html>
  );
}
